// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDQZrHfsFJpK3SJYKZlwcNbh6muumyUew',
    appId: '1:196191083704:web:43c1fad19c187a5c0b284d',
    messagingSenderId: '196191083704',
    projectId: 'elconnected',
    authDomain: 'elconnected.firebaseapp.com',
    storageBucket: 'elconnected.appspot.com',
    measurementId: 'G-R9SGPZQ6YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI0sAHSSO-dI3I1LwABuqBb9yuR1I-jL8',
    appId: '1:196191083704:android:1796a01dabbea7fa0b284d',
    messagingSenderId: '196191083704',
    projectId: 'elconnected',
    storageBucket: 'elconnected.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_9nhyK5vS8Ypv0vJl5i5NNS1NwZtePAw',
    appId: '1:196191083704:ios:3bb631b16ce938c70b284d',
    messagingSenderId: '196191083704',
    projectId: 'elconnected',
    storageBucket: 'elconnected.appspot.com',
    iosBundleId: 'com.example.elconnected',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_9nhyK5vS8Ypv0vJl5i5NNS1NwZtePAw',
    appId: '1:196191083704:ios:3bb631b16ce938c70b284d',
    messagingSenderId: '196191083704',
    projectId: 'elconnected',
    storageBucket: 'elconnected.appspot.com',
    iosBundleId: 'com.example.elconnected',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDQZrHfsFJpK3SJYKZlwcNbh6muumyUew',
    appId: '1:196191083704:web:1302ef00efa91d520b284d',
    messagingSenderId: '196191083704',
    projectId: 'elconnected',
    authDomain: 'elconnected.firebaseapp.com',
    storageBucket: 'elconnected.appspot.com',
    measurementId: 'G-MGZWCDD621',
  );
}
